language: go

go:
  - 1.11.x

os:
  - linux
  - osx

git:
  depth: 1

env:
  global:
    - NAME=gotop

install: true
script:
  - bash ci/script.sh

matrix:
  include:
    # Linux
    - env: GOOS=linux GOARCH=amd64
      os: linux
    - env: GOOS=linux GOARCH=386
      os: linux
    - env: GOOS=linux GOARCH=arm GOARM=5
      os: linux
    - env: GOOS=linux GOARCH=arm GOARM=6
      os: linux
    - env: GOOS=linux GOARCH=arm GOARM=7
      os: linux
    - env: GOOS=linux GOARCH=arm64
      os: linux

    # OSX
    - env: GOOS=darwin GOARCH=amd64
      os: osx
    - env: GOOS=darwin GOARCH=386
      os: osx

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
